### ISSUE TITLE
No module named 'src.vespag.runner.embeddings'

### ISSUE THREAD

**Issue by gavinmdouglas** [JSchlensok/VespaG#4]
Hi there,

I just ran into this problem when running the predict command (`python -m src.vespag.runner.predict`) with the latest developmental version:

```
Traceback (most recent call last):
  File "/home6/gmdougla/local/miniforge3/envs/vespag/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home6/gmdougla/local/miniforge3/envs/vespag/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home6/gmdougla/local/prg/VespaG/src/vespag/runner/predict.py", line 13, in <module>
    from src.vespag.runner.embeddings import get_esm2_embeddings
ModuleNotFoundError: No module named 'src.vespag.runner.embeddings
```

It looks like `embeddings.py` was moved to `src/vespa/data`, but also that the `get_esm2_embeddings` function was removed or renamed and put elsewhere.

I can confirm that that running `python -m src.vespag.runner.predict  -h` works as expected when I revert to an earlier commit (3a781ade47c526d00530582f6447f182e81089e8).

Cheers,

Gavin

**Comment by JSchlensok** [comment]
Hi Gavin, thanks for reporting this! The repo wasn't completely ready for public usage, but should be good to go now - let me know if the error persists.

Please note that invocation has changed to `python -m vespag predict ...` now and some parameter names have *slightly* changed!

**Comment by gavinmdouglas** [comment]
Hi @JSchlensok , no worries -- I figured!

Thanks -- it seems to be working now.


Cheers,

Gavin
