### ISSUE TITLE
Clarification of ESM2 embeddings

### ISSUE THREAD

**Issue by brycejoh16** [JSchlensok/VespaG#6]
Thank you for being so open with your work. 

Could you please clarify how the ESM-2 embeddings on zenodo are stored. 

For example, for GFP I get a 238 by 2560 vector matrix. I'm assuming each row corresponds a position. So then each vector a single mutant is 128 in length. But what is the order of the single mutants for each row then? 

Also how are embeddings calculated for multi-mutants? 

Thank you so much for providing this resource. Great work! 

- Bryce

**Comment by C-Marquet** [comment]
Hi Bryce,

Thanks for your interest in our work and reaching out! 

The file you are describing are the [ESM-2 embeddings](https://www.science.org/doi/10.1126/science.ade2574). You are right - the format is Lx2560 (length x embedding dimension). The embedding dimension is fixed to 2560 (please see `esm2_t36_3B_UR50D` in this [table](https://github.com/facebookresearch/esm?tab=readme-ov-file#pre-trained-models-)). The idea of VespaG is to only input the ESM-2 embeddings for the wild type and then predict the a mutational landscape of 20xL. So the embeddings are only for the wild type sequence and if you wanted embeddings for mutated sequences, you would have to run ESM-2 for those sequences.

If you want the VespaG prediction scores for the ProteinGym benchmark set, you can download the file `proteingym_performance_vespag.csv` from [zenodo](https://zenodo.org/records/11085958/files/vespag_proteingym_rawpreds_by_training_dataset.zip?download=1) with the file `raw_preds_human.csv ` containing the columns 'DMS_id', 'mutation', 'DMS_score', 'VespaG'. The column 'DMS_id' has the identifiers for the deep mutational scans in the ProteinGym benchmark. The column 'mutation' consists of the variants/mutations of the respective experiments, following the format: _fromAA + position/index + toAA_ (f.e. _296A_) with _fromAA_ being the wild type amino acid at a certain position and _toAA_ the respective mutation. The column 'DMS_score' lists the experimental score and the column 'VespaG' the predicted score.

Multi-mutations have the format _P191K:Y209W_ and are scored by averaging the respective single mutations.

Hopefully this helps, let us know if you need any further information!

Best,
Céline

**Comment by JSchlensok** [comment]
Closing this for now.
