### ISSUE TITLE
VespaG import error

### ISSUE THREAD

**Issue by CallMeMisterOwl** [JSchlensok/VespaG#8]
Due to technical issue I'm currently not able to access my usual work environment. Hence I tried using VespaG on my local machine. After cloning the repository and installing all dependencies, I get following error message when running VespaG with the `example.fasta`:

```
Traceback (most recent call last):
  File "/usr/local/envs/VespaG/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/envs/VespaG/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/vespag/__main__.py", line 8, in <module>
    from .eval import eval
  File "/content/vespag/eval/eval.py", line 15, in <module>
    from vespag.utils.proteingym import PROTEINGYM_CHANGED_FILENAMES
ModuleNotFoundError: No module named 'vespag.utils.proteingym' 
```
After changing line 15 in `vespag/eval/eval.py ` from `from vespag.utils.proteingym import PROTEINGYM_CHANGED_FILENAMES` to `from vespag.utils import PROTEINGYM_CHANGED_FILENAMES `, everything works as intended now.

**Comment by JSchlensok** [comment]
@CallMeMisterOwl thanks for reporting this, sorry for the late reply. There were a couple changes to the utils module I hadn't pushed, 89db27282a1b9d6790304b9c516ab362135870c1 should fix this. Can you pull and verify that your imports now work?

**Comment by JSchlensok** [comment]
@mohitpandey92 thanks to you too for reporting. 24001b5f12c0aec26b30b5347897f7ff02455b9e fixes your issue.
